syntax = "proto3";

package signage.hardware.v1.display_group;

import "hardware/v1/display_group/display_group.common.proto";

service DisplayGroupService {
  rpc CreateDisplayGroup(CreateDisplayGroupRequest) returns (DisplayGroup) {}
  rpc GetDisplayGroup(GetDisplayGroupRequest) returns (DisplayGroup) {}
  rpc ListDisplayGroups(ListDisplayGroupsRequest) returns (ListDisplayGroupsResponse) {}
  rpc UpdateDisplayGroup(UpdateDisplayGroupRequest) returns (DisplayGroup) {}
  rpc DeleteDisplayGroup(DeleteDisplayGroupRequest) returns (DeleteDisplayGroupResponse) {}
}
