syntax = "proto3";

package signage.studio.v1.layer;

import "common/v1/types.proto";
import "studio/v1/playlist/playlist.common.proto";
import "studio/v1/media/media.common.proto";
import "studio/v1/layer/item_override/layer_item_override.common.proto";

message LayerPlaylist {
  string id = 1;
  string layer_id = 2;
  string playlist_id = 3;
  signage.studio.v1.playlist.Playlist playlist = 4;
  int32 start_time_seconds = 5;
  int32 duration_seconds = 6;
  string transition_type = 7;
  int32 order_index = 8;
  repeated LayerPlaylistItemOverride item_overrides = 9;
  string created_at = 10;
  string media_item_id = 11;
  signage.studio.v1.media.MediaItem media_item = 12;
  bool is_muted = 13;
  int32 volume_level = 14;
}


message CreateLayerBlockRequest {
  string layer_id = 1;
  optional string playlist_id = 2;
  optional string media_item_id = 3;
  int32 start_time_seconds = 4;
  int32 duration_seconds = 5;
}

message GetLayerBlockRequest {
  string id = 1;
}

message ListLayerBlocksRequest {
  int32 page = 1;
  int32 limit = 2;
  optional string layer_id = 3;
}

message ListLayerBlocksResponse {
  repeated LayerPlaylist blocks = 1;
  int32 total = 2;
  int32 page = 3;
  int32 limit = 4;
}

message UpdateLayerBlockRequest {
  string id = 1;
  optional int32 start_time_seconds = 2;
  optional int32 duration_seconds = 3;
  optional string transition_type = 4;
  optional int32 order_index = 5;
  optional bool is_muted = 6;
  optional int32 volume_level = 7;
}

message DeleteLayerBlockRequest {
  string id = 1;
}

message DeleteLayerBlockResponse {
  bool success = 1;
}