ALTER TABLE devices DROP COLUMN IF EXISTS schedule_id;
ALTER TABLE display_groups DROP COLUMN IF EXISTS schedule_id;
DROP TABLE IF EXISTS schedule_events CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
