syntax = "proto3";

package signage.studio.v1.playlist;

import "studio/v1/playlist/playlist.common.proto";

service PlaylistService {
  // Playlist CRUD
  rpc CreatePlaylist(CreatePlaylistRequest) returns (Playlist);
  rpc GetPlaylist(GetPlaylistRequest) returns (Playlist);
  rpc ListPlaylists(ListPlaylistsRequest) returns (ListPlaylistsResponse);
  rpc UpdatePlaylist(UpdatePlaylistRequest) returns (Playlist);
  rpc DeletePlaylist(DeletePlaylistRequest) returns (DeletePlaylistResponse);

  // Playlist Items CRUD & Sequencing
  rpc AddPlaylistItem(AddPlaylistItemRequest) returns (PlaylistItem);
  rpc UpdatePlaylistItem(UpdatePlaylistItemRequest) returns (PlaylistItem);
  rpc RemovePlaylistItem(RemovePlaylistItemRequest) returns (RemovePlaylistItemResponse);
  rpc ReorderPlaylistItems(ReorderPlaylistItemsRequest) returns (ReorderPlaylistItemsResponse);
}
