syntax = "proto3";

package signage.iam.v1.permission;

import "iam/v1/permission/permission.common.proto";

service PermissionService {
  rpc CreatePermission(CreatePermissionRequest) returns (Permission);
  rpc GetPermission(GetPermissionRequest) returns (Permission);
  rpc GetPermissionByCode(GetPermissionByCodeRequest) returns (Permission);
  rpc ListPermissions(ListPermissionsRequest) returns (ListPermissionsResponse);
  rpc UpdatePermission(UpdatePermissionRequest) returns (Permission);
  rpc DeletePermission(DeletePermissionRequest) returns (DeletePermissionResponse);
  rpc CheckUserPermission(CheckUserPermissionRequest) returns (CheckUserPermissionResponse);
}
