syntax = "proto3";

package signage.studio.v1.layer;

import "common/v1/types.proto";
import "studio/v1/layer/block/layer_block.common.proto";

message Layer {
  string id = 1;
  string layout_id = 2;
  string name = 3;
  int32 x = 4;
  int32 y = 5;
  int32 width = 6;
  int32 height = 7;
  int32 z_index = 8;
  repeated LayerPlaylist blocks = 9;
  string background_color = 11;
  string created_at = 12;
  string updated_at = 13;
}


message CreateLayerRequest {
  string layout_id = 1;
  string name = 2;
  int32 x = 3;
  int32 y = 4;
  int32 width = 5;
  int32 height = 6;
  int32 z_index = 7;
  string background_color = 9;
}

message GetLayerRequest {
  string id = 1;
}

message ListLayersRequest {
  int32 page = 1;
  int32 limit = 2;
  optional string search = 3;
  optional string layout_id = 4;
}

message ListLayersResponse {
  repeated Layer layers = 1;
  int32 total = 2;
  int32 page = 3;
  int32 limit = 4;
}

message UpdateLayerRequest {
  string id = 1;
  string name = 2;
  int32 x = 3;
  int32 y = 4;
  int32 width = 5;
  int32 height = 6;
  int32 z_index = 7;
  string background_color = 9;
}

message DeleteLayerRequest {
  string id = 1;
}

message DeleteLayerResponse {
  bool success = 1;
}