syntax = "proto3";

package signage.studio.v1.schedule;

import "studio/v1/schedule/schedule.common.proto";

service ScheduleService {
  rpc CreateSchedule(CreateScheduleRequest) returns (Schedule) {}
  rpc GetSchedule(GetScheduleRequest) returns (Schedule) {}
  rpc ListSchedules(ListSchedulesRequest) returns (ListSchedulesResponse) {}
  rpc UpdateSchedule(UpdateScheduleRequest) returns (Schedule) {}
  rpc DeleteSchedule(DeleteScheduleRequest) returns (DeleteScheduleResponse) {}
  
  rpc AddScheduleEvent(AddScheduleEventRequest) returns (ScheduleEvent) {}
  rpc RemoveScheduleEvent(RemoveScheduleEventRequest) returns (RemoveScheduleEventResponse) {}
}
