syntax = "proto3";

package signage.studio.v1.media;

import "studio/v1/media/media.common.proto";

service MediaService {
  rpc CreateMedia(CreateMediaRequest) returns (MediaItem);
  rpc GetMedia(GetMediaRequest) returns (MediaItem);
  rpc ListMedia(ListMediaRequest) returns (ListMediaResponse);
  rpc UpdateMedia(UpdateMediaRequest) returns (MediaItem);
  rpc DeleteMedia(DeleteMediaRequest) returns (DeleteMediaResponse);
  rpc UploadMediaChunk(UploadMediaChunkRequest) returns (UploadMediaChunkResponse);
  rpc FinalizeUpload(FinalizeUploadRequest) returns (UploadMediaChunkResponse);
  rpc GetMediaFile(GetMediaFileRequest) returns (GetMediaFileResponse);
  rpc StreamMediaFile(StreamMediaFileRequest) returns (stream StreamMediaFileResponse);
}

