syntax = "proto3";

package signage.iam.v1.role_group;

import "iam/v1/role_group/role_group.common.proto";

service RoleGroupService {
  rpc CreateRoleGroup(CreateRoleGroupRequest) returns (RoleGroup);
  rpc GetRoleGroup(GetRoleGroupRequest) returns (RoleGroup);
  rpc ListRoleGroups(ListRoleGroupsRequest) returns (ListRoleGroupsResponse);
  rpc UpdateRoleGroup(UpdateRoleGroupRequest) returns (RoleGroup);
  rpc DeleteRoleGroup(DeleteRoleGroupRequest) returns (DeleteRoleGroupResponse);
  rpc AssignRolesToGroup(AssignRolesToGroupRequest) returns (AssignRolesToGroupResponse);
}
