syntax = "proto3";

package signage.iam.v1.role_group;

import "common/v1/types.proto";
import "iam/v1/role/role.common.proto";

message RoleGroup {
  string id = 1;
  string name = 2;
  string slug = 3;
  string description = 4;
  repeated signage.iam.v1.role.Role roles = 5;
  string created_at = 6;
  string updated_at = 7;
}

message CreateRoleGroupRequest {
  string name = 1;
  string slug = 2;
  string description = 3;
  repeated string role_ids = 4;
}

message GetRoleGroupRequest {
  string id = 1;
}

message ListRoleGroupsRequest {
  signage.common.v1.PaginationRequest pagination = 1;
  string search = 2;
}

message ListRoleGroupsResponse {
  repeated RoleGroup items = 1;
  signage.common.v1.PaginationResponse pagination = 2;
}

message UpdateRoleGroupRequest {
  string id = 1;
  string name = 2;
  string description = 3;
  repeated string role_ids = 4;
}

message DeleteRoleGroupRequest {
  string id = 1;
}

message DeleteRoleGroupResponse {
  bool success = 1;
}

message AssignRolesToGroupRequest {
  string role_group_id = 1;
  repeated string role_ids = 2;
}

message AssignRolesToGroupResponse {
  bool success = 1;
  RoleGroup role_group = 2;
}
